@startuml

title **항공사(Airline) Transaction Credential 조회**

participant "TransactionCredentialService[Airline]" as airlineTransactionCredential
database Mapper as mapper
database MySQL as mysql

' airlineTransactionCredential start ================================================================================
?o-> airlineTransactionCredential ++ : getCredential\n(TransactionParams)

' MySQL Select
group #Aqua MySQL Select getCredential[Airline]
    note right of airlineTransactionCredential: ""TransactionCredentialMapper""
    airlineTransactionCredential -> mapper ++ : getCredential[Airline](agencyId, providerCode, airlineCode)
    mapper -> mysql ++ : SELECT TB_AG_CREDENCIAL_[Airline] ...
    mapper <-- mysql -- : ""Credential[Airline]""
    airlineTransactionCredential <-- mapper -- : ""Credential[Airline]""
end

?o<-- airlineTransactionCredential: ""Credential[Airline]""
' airlineTransactionCredential end ================================================================================
@enduml