@@startuml

할인정책확인 -[#red]> 데이터베이스: 주차장 할인권 타입별, 그룹별 사용 합산 데이터 조회 요청
할인정책확인 <-[#0000FF]- 데이터베이스: 조회 요청 결과 응답
note right #GreenYellow: 타입별__(T:분할인, M:금액할인, P:비율할인)__\n 할인 정책 그룹 별 합산 데이터
할인정책확인 -[#red]> 데이터베이스: 할인 정책 리스트 조회 요청
할인정책확인 <-[#0000FF]- 데이터베이스: 조회 요청 결과 응답
note right #GreenYellow: 할인 정책(주차장 기본 및 해당 스토어)\n 최대 제한 값 리스트 데이터
== 데이터 가공 ==
group 정책 리스트 가공
    
    alt 스토어 정책 리스트 추출
        note right of 할인정책확인 #aqua
            할인 정책 리스트에서 현재 스토어와 같은 정책만 추출
        end note
    end

    alt 할인 정책 그룹 리스트 추출
        note right of 할인정책확인 #aqua
            스토어 정책 리스트에서 제한그룹이 0이 아닌것만 추출
        end note
    end

    alt 할인 공통 정책 리스트 추출
        note right of 할인정책확인 #aqua
            할인 정책 리스트에서 스토어가 0인 것만 추출
        end note
    end

    group 스토어 정책 리스트가 있을때 같은 정책 제거 리스트 생성
        loop 스토어 정책 리스트가 있으면 루프
            loop 할인 정책 그룹 리스트가 있으면 루프
                note right of 할인정책확인 #FFAAAA: //징수유형//**[pklp_charge_type]**__(0:전체 1:유료 2:무료)__\n//최대제한유형//**[pklp_limit_type]**__(1:시간(분단위) 2:금액 3:비율(퍼센트) 4:횟수)__\n이 같고 제한그룹이 0 인것 제거
            end

            loop 할인 공통 정책 리스트가 있으면 루프
                note right of 할인정책확인 #FFAAAA: //징수유형//**[pklp_charge_type]**__(0:전체 1:유료 2:무료)__\n//최대제한유형//**[pklp_limit_type]**__(1:시간(분단위) 2:금액 3:비율(퍼센트) 4:횟수)__\n이 같은 것 제거
            end
        end
    end
end
== 할인 정책 확인 데이터 가공 ==
note right of 할인정책확인 #aqua: 주차장 전체 사용내역 합산 데이터 추출
loop 가공된 할인 정책 리스트 루프
    note right of 할인정책확인 #aqua: 할인 정책 그룹에 해당하는 사용내역 합산 데이터 추출
    alt 할인정책확인
        note right of 할인정책확인
            //징수유형//**[pklp_charge_type]**__(0:전체 1:유료 2:무료)__
            이 전체가 아니고 같은 유형이 아니면 패스
            (전체는 모두(유료, 무료) 포함이므로 조건 제외)
        end note
    end
    alt 할인정책확인
        note right of 할인정책확인
            //최대제한유형//**[pklp_limit_type]**__(1:시간(분단위) 2:금액 3:비율(퍼센트) 4:횟수)__
            이 횟수가 아니고 할인타입과 같지 않으면 패스
            (횟수는 할인타입이 아니므로 조건 제외)
        end note
    end
end
== 할인 정책 제한 확인 ==
alt 할인 정책 그룹[pklp_limit_group]이 있으면
    note right of 할인정책확인: 할인 정책 그룹 사용내역 합산 데이터로 제한확인
else 할인 정책 그룹이 없으면
    note right of 할인정책확인: 주차장 전체 사용내역 합산 데이터로 제한확인
end
note right of 할인정책확인 #Orange : **4:횟수는 //초과값허용 여부//[is_over]의 영향을 받지않음**
alt //초과값허용 여부//**[is_over]**가 //허용//**[<color blue>true</color>]**인 경우
    note right of 할인정책확인: 현재 사용내역만으로 제한확인
else //초과값허용 여부//**[is_over]**가 //허용이 아닌//**[<color red>false</color>]** 경우
    note right of 할인정책확인: 현재 사용내역 + (사용 요청값 * 사용 요청횟수)로 제한확인 
end

alt 할인 정책 제한 확인
    note right of 할인정책확인
        //최대제한유형//**[pklp_limit_type]**__(1:시간(분단위) 2:금액 3:비율(퍼센트) 4:횟수)__
        에 따라 제한확인
    end note
    note right of 할인정책확인
        제한값 초과시 초과 메세지 리턴
    end note
end

@@enduml